/* Generated By:JJTree: Do not edit this line. BSHFormalComment.java */

package de.droidcachebox.locator.bsh;

public class BSHFormalComment extends SimpleNode {
    /**
     *
     */
    private static final long serialVersionUID = 1L;
    public String text;

    public BSHFormalComment(int id) {
        super(id);
    }

}
